### ISSUE TITLE
Image Slider disappears if there is only one image

### ISSUE THREAD

**Issue by abdrasulov** [smashingboxes/OwlCarousel2#858]
With the following options:
```javascript
{
	loop: true,
	autoplay: true,
	items: 1
}
```
Image slider disappears if there is only one image.

**Comment by PixelT** [comment]
+1

**Comment by iamkeir** [comment]
Could you explain the context? I think this is 'by design' - why would you need to initiate the slider for a single item?

**Comment by iamkeir** [comment]
Ah, just tried this myself - I misunderstood. I can confirm that with the above settings, the carousel disappears entirely.

**Comment by PixelT** [comment]
A simple example:
I include the OwlCarousel on WordPress.
In each category ,at the top - user can define slides.
But what when user define at specific category just one slide? Page breaks down...
I tested other popular slider plugins, and they haven't problem with display one slide - so imo it qualifies as a bug

**Comment by iandonovan** [comment]
Can someone produce a jsbin or fiddle to replicate the issue?

**Comment by iamkeir** [comment]
Here ya go: http://codepen.io/iamkeir/pen/gpXONe

**Comment by mikehdt** [comment]
Issues #539, #548 and #667 are all duplicates of this issue. There is a fix in #667 https://github.com/smashingboxes/OwlCarousel2/issues/667#issuecomment-69500946 which patches the code and reliably fixes it, without resorting to other hacks like "If there is only one item, do not initialise Owl Carousel".

**Comment by greg5green** [comment]
The code listed in #667 looks like it'll work. Someone submit a PR and I'll merge and publish quickly

**Comment by iamkeir** [comment]
I had a look at #667 and forked to fix but I cannot find those lines of code in a global find - could the core code have been changed since that was posted in January? Or am I being a numpty?

**Comment by greg5green** [comment]
@iamkeir Thanks for the attempt to fix -- I can't find it now either, but I swear I saw it a week ago when I took a look at this issue!

On a whim though, I upgraded your codepen to the newest beta 3 (http://codepen.io/anon/pen/oXEWPM) and it was fixed by this newest release.

You can grab it from http://smashingboxes.github.io/download/owl.carousel.2.0.0-beta.3.zip or bower!

**Comment by iamkeir** [comment]
Ace, even better :)

**Comment by PixelT** [comment]
@greg5green 
update the beta version for download on http://www.owlcarousel.owlgraphic.com/ :)

**Comment by greg5green** [comment]
@PixelT It's something we're working on! We took over this project a few months ago and are still trying to get some of these basic administrative things set up.

For now, you can download the newest version from http://smashingboxes.github.io/OwlCarousel2/download/owl.carousel.2.0.0-beta.3.zip and its also available on bower.

**Comment by leecollings** [comment]
Has this been fixed? I'm still getting the same issue in the current beta 2.4 version, and the URL by greg5green is returning a 404.

So right now on pages with just one slide, no slider is showing at all. What's the fix for this, and where can it be downloaded from?

**Comment by Indrasis** [comment]
check if more than one image is present or not. If yes then initialize owl carousel. otherwise not.

**Comment by BrettGregson** [comment]
Turn loop off and it works with one slide

**Comment by darrenbachan** [comment]
Is there any update on this? I'm using whatever the latest is on the website and running into this issue.
